from dotenv import load_dotenv
import os


load_dotenv()


ELASTICSEARCH_URL= os.getenv("ELASTICSEARCH_URL")
INDEX_NAME_HUGGINGFACE= os.getenv("INDEX_NAME_HUGGINGFACE")
INDEX_NAME_GEMINI= os.getenv("INDEX_NAME_GEMINI")
INDEX_NAME_OPENAI= os.getenv("INDEX_NAME_OPENAI")
SITEMAP_URL= os.getenv("SITEMAP_URL")
HUGGINGFACE_EMBEDDING_MODEL_NAME= os.getenv("HUGGINGFACE_EMBEDDING_MODEL_NAME")
GEMINI_EMBEDDING_MODEL_NAME= os.getenv("GEMINI_EMBEDDING_MODEL_NAME")
OPENAI_EMBEDDING_MODEL_NAME= os.getenv("OPENAI_EMBEDDING_MODEL_NAME")
GEMINI_API_KEY= os.getenv("GEMINI_API_KEY")
OPENAI_API_KEY= os.getenv("OPENAI_API_KEY")